### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by stephenmathieson**
A bit unnecessary, but can't hurt :)

### CODE REVIEW

**Comment by jwerle** [comment]
tests never hurt! (as long as they are testing the correct stuff, haha) - LGTM btw

cc @willemt

**Comment by stephenmathieson** [comment]
assuming Willemt is cool with it, we could enable travis too :)

**Comment by jwerle** [comment]
+1

**Comment by willemt** [comment]
Looks good, 100% test coverage!

Lets add travis too :)

**Comment by jwerle** [comment]
:D

**Pull request merged**
